server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
      ## REST CLIENT -> http://localhost:4004/api/patients
      ## API GATEWAY -> http://patient-service:4000/patients
      ## PATIENT SERVICE (SPRING BOOT APP) -> patients -> Patients Array
      - id: patient-service-route
        uri: http://patient-service:4000
        predicates:
          - path=/api/patients/**
        filters:
          - strip-prefix=1

      - id: api-docs-patient-route
        uri: http://patient-service:4000
        predicates:
            - path=/api-docs/patients
        filters:
          - rewrite-path=/api-docs/patients,/v3/api-docs