server:
  port: 4004

spring:
  reactor:
    netty:
      http:
        server:
          accessLogEnabled=true:
  jmx:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      metrics:
        enabled: true
      routes:
      ## REST(OR FRONTEND) CLIENT -> http://localhost:4004/api/patients
      ## API GATEWAY -> http://patient-service:4000/patients
      ## PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array
      - id: patient-service-route
        uri: http://patient-service:4000
        predicates:
          - Path=/api/patients,/api/patients/**
        filters:
         - StripPrefix=1
      ## REST-CLIENT -> http://localhost:4004/api-docs/patients
      ## API-GATEWAY -> http://patient-service/4000/v3/api-docs
      - id: patient-service-swagger
        uri: http://patient-service:4000
        predicates:
          - Path=/patient-service/swagger-ui/**
        filters:
          - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG


management.endpoints.web.exposure.include: '*'