server:
  port: 4004 #Gateway listens on port 4004

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          # Route for /api/patients/** to patient-service
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
              - Path=/api/patients/**
              filters:
              - StripPrefix=1
          # Route for /api/docs/patients to patient-service /v3/api-docs
            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
              - Path=/api-docs/patients
              filters:
              - RewritePath=/api-docs/patients,/v3/api-docs
            - id: api-swagger-patient-route
              uri: http://patient-service:4000
              predicates:
              - Path=/swagger-patients
              filters:
              - RewritePath=/swagger-patients,/swagger-ui/index.html

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
