services:
  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5001:5432"
    volumes:
      - ./auth-data:/var/lib/postgresql
    networks:
      - internal

networks:
  internal:
    external: true