services:
  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5001:5432"
    volumes:
      - ./auth-data:/var/lib/postgresql
    networks:
      - internal
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "4005:4005"
    environment:
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: generate-from--internet
    networks:
      - internal
    depends_on:
      - auth-service-db

networks:
  internal:
    external: true