services:
  postgres:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5000:5432"
    volumes:
      - /home/syzana/Documents/docker-binded-mounts/db_volumes/patient-service-db/
      - /var/lib/postgresql/data\
